# Generated by Django 3.2.12 on 2022-02-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bribes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bribe',
            name='refund_tx_hash',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bribe',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending unlock time'), (1, 'Invalid bribe'), (2, 'Active bribe'), (3, 'Returned'), (4, 'Pending unlock time to return'), (5, 'Failed claim'), (6, 'Conversion failed'), (7, 'Failed return')]),
        ),
    ]
