# Generated by Django 3.2.12 on 2022-02-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bribes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedByAssetBribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_key', models.CharField(max_length=56)),
                ('asset_code', models.CharField(max_length=12)),
                ('asset_issuer', models.CharField(max_length=56)),
                ('start_at', models.DateTimeField(null=True)),
                ('stop_at', models.DateTimeField(null=True)),
                ('total_reward_amount', models.DecimalField(decimal_places=7, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
