# Generated by Django 3.2.12 on 2022-02-24 13:14

from django.db import migrations, models
import django.db.models.deletion


def migrate_marker_key(apps, schema_editor):
    MarketKey = apps.get_model("bribes", "MarketKey")
    Bribe = apps.get_model("bribes", "Bribe")
    AggregatedByAssetBribe = apps.get_model("bribes", "AggregatedByAssetBribe")

    for bribe in Bribe.objects.all():
        instance, _ = MarketKey.objects.get_or_create(market_key=bribe.market_key)
        bribe.market_key_instance = instance
        bribe.save()

    for bribe in AggregatedByAssetBribe.objects.all():
        instance, _ = MarketKey.objects.get_or_create(market_key=bribe.market_key)
        bribe.market_key_instance = instance
        bribe.save()


def migrate_marker_key_backward(apps, schema_editor):
    MarketKey = apps.get_model("bribes", "MarketKey")
    Bribe = apps.get_model("bribes", "Bribe")
    AggregatedByAssetBribe = apps.get_model("bribes", "AggregatedByAssetBribe")

    for bribe in Bribe.objects.all():
        bribe.market_key = bribe.market_key_instance.market_key
        bribe.save()

    for bribe in AggregatedByAssetBribe.objects.all():
        bribe.market_key = bribe.market_key_instance.market_key
        bribe.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bribes', '0002_aggregatedbyassetbribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketKey',
            fields=[
                ('market_key', models.CharField(max_length=56, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='aggregatedbyassetbribe',
            name='market_key_instance',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aggregated_bribes', to='bribes.marketkey'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bribe',
            name='market_key_instance',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bribes', to='bribes.marketkey'),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_marker_key, migrate_marker_key_backward),
        migrations.RemoveField(
            model_name='aggregatedbyassetbribe',
            name='market_key',
        ),
        migrations.RemoveField(
            model_name='bribe',
            name='market_key',
        ),
        migrations.RenameField(
            model_name='aggregatedbyassetbribe',
            old_name='market_key_instance',
            new_name='market_key',
        ),
        migrations.RenameField(
            model_name='bribe',
            old_name='market_key_instance',
            new_name='market_key',
        ),
    ]
