# Generated by Django 3.2.12 on 2022-02-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bribes', '0003_auto_20220224_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedbyassetbribe',
            name='aqua_total_reward_amount_equivalent',
            field=models.DecimalField(decimal_places=7, max_digits=20, null=True),
        ),
    ]
