# Generated by Django 3.2.12 on 2022-03-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bribes', '0004_aggregatedbyassetbribe_aqua_total_reward_amount_equivalent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bribe',
            name='aqua_total_reward_amount_equivalent',
            field=models.DecimalField(decimal_places=7, max_digits=20, null=True),
        ),
    ]
