# Generated by Django 3.2.12 on 2022-03-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bribes', '0005_bribe_aqua_total_reward_amount_equivalent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bribe',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending unlock time'), (1, 'Invalid bribe'), (2, 'Active bribe'), (3, 'Returned'), (4, 'Pending unlock time to return'), (5, 'Failed claim'), (6, 'Conversion failed'), (7, 'Failed return'), (8, 'Finished')]),
        ),
    ]
