# Generated by Django 3.2.12 on 2022-05-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bribes', '0006_alter_bribe_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bribe',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
