# Generated by Django 3.2.14 on 2025-06-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bribes', '0007_alter_bribe_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bribe',
            name='is_amm_protocol',
            field=models.BooleanField(default=False, help_text='AMM Protocol bribes are created using a fraction of collected protocol fees'),
        ),
    ]
