# Generated by Django 3.2.21 on 2025-08-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bribes', '0008_bribe_is_amm_protocol_bribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketkey',
            name='raw_asset1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='marketkey',
            name='raw_asset2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
