# Generated by Django 3.2.12 on 2022-02-24 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bribes', '0003_auto_20220224_1314'),
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votesnapshot',
            name='market_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bribes.marketkey'),
        ),
    ]
