# Generated by Django 3.2.12 on 2022-02-28 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bribes', '0004_aggregatedbyassetbribe_aqua_total_reward_amount_equivalent'),
        ('rewards', '0002_alter_votesnapshot_market_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='bribe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bribes.aggregatedbyassetbribe'),
        ),
    ]
