# Generated by Django 3.2.12 on 2022-02-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_alter_payout_bribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHolderBalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=255)),
                ('asset_code', models.CharField(max_length=12)),
                ('asset_issuer', models.CharField(max_length=56)),
                ('balance', models.DecimalField(decimal_places=7, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
