# Generated by Django 3.2.12 on 2022-03-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bribes', '0004_aggregatedbyassetbribe_aqua_total_reward_amount_equivalent'),
        ('rewards', '0004_assetholderbalancesnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votesnapshot',
            name='snapshot_time',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='votesnapshot',
            unique_together={('snapshot_time', 'market_key', 'voting_account')},
        ),
    ]
