# Generated by Django 3.2.12 on 2022-03-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0005_auto_20220301_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetholderbalancesnapshot',
            name='account',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assetholderbalancesnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='message',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('failed', 'failed')], db_index=True, default='success', max_length=30),
        ),
    ]
