# Generated by Django 3.2.12 on 2022-03-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0006_auto_20220321_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votesnapshot',
            name='snapshot_time',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='votesnapshot',
            name='voting_account',
            field=models.CharField(db_index=True, max_length=56),
        ),
    ]
