# Generated by Django 3.2.21 on 2025-02-24 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0007_auto_20220321_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimableBalance',
            fields=[
                ('claimable_balance_id', models.CharField(max_length=96, primary_key=True, serialize=False)),
                ('asset_code', models.CharField(max_length=12)),
                ('asset_issuer', models.CharField(max_length=56)),
                ('amount', models.DecimalField(decimal_places=7, default=0, max_digits=20)),
                ('sponsor', models.CharField(db_index=True, max_length=56)),
                ('owner', models.CharField(db_index=True, max_length=56)),
                ('paging_token', models.CharField(blank=True, max_length=32)),
                ('last_modified_time', models.DateTimeField(null=True)),
                ('last_modified_ledger', models.PositiveIntegerField()),
                ('loaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='votesnapshot',
            name='is_delegated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='votesnapshot',
            name='has_delegation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='votesnapshot',
            unique_together={('snapshot_time', 'market_key', 'voting_account', 'is_delegated', 'has_delegation')},
        ),
        migrations.CreateModel(
            name='Claimant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(db_index=True, max_length=56)),
                ('raw_predicate', models.TextField()),
                ('claimable_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimants', to='rewards.claimablebalance')),
            ],
        ),
    ]
