# Generated by Django 3.2.21 on 2025-07-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bribes', '0008_bribe_is_amm_protocol_bribe'),
        ('rewards', '0008_auto_20250224_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='votesnapshot',
            name='delegate_owner',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=56, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='votesnapshot',
            unique_together={('snapshot_time', 'market_key', 'voting_account', 'is_delegated', 'has_delegation', 'delegate_owner')},
        ),
    ]
