# Generated by Django 3.2.21 on 2025-07-27 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0009_auto_20250707_1530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClaimableBalance',
            new_name='OldClaimableBalance',
        ),
        migrations.RenameModel(
            old_name='Claimant',
            new_name='OldClaimant',
        ),
    ]
