# Generated by Django 3.2.21 on 2025-07-27 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0010_auto_20250727_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldclaimablebalance',
            name='sponsor',
            field=models.CharField(max_length=56),
        ),
        migrations.AlterField(
            model_name='oldclaimablebalance',
            name='loaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='oldclaimablebalance',
            name='owner',
            field=models.CharField(max_length=56),
        ),
        migrations.AlterField(
            model_name='oldclaimant',
            name='destination',
            field=models.CharField(max_length=56),
        ),
        migrations.RenameField(
            model_name='oldclaimant',
            old_name='claimable_balance',
            new_name='old_claimable_balance',
        ),
        migrations.AlterField(
            model_name='oldclaimant',
            name='old_claimable_balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_claimants', to='rewards.oldclaimablebalance'),
        ),
    ]
