# Generated by Django 3.2.21 on 2025-07-27 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0011_auto_20250727_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldclaimant',
            name='old_claimable_balance',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ClaimableBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimable_balance_id', models.CharField(max_length=96)),
                ('asset_code', models.CharField(max_length=12)),
                ('asset_issuer', models.CharField(max_length=56)),
                ('amount', models.DecimalField(decimal_places=7, default=0, max_digits=20)),
                ('sponsor', models.CharField(db_index=True, max_length=56)),
                ('owner', models.CharField(db_index=True, max_length=56)),
                ('paging_token', models.CharField(blank=True, max_length=32)),
                ('last_modified_time', models.DateTimeField(null=True)),
                ('last_modified_ledger', models.PositiveIntegerField()),
                ('loaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Claimant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(db_index=True, max_length=56)),
                ('raw_predicate', models.TextField()),
                ('claimable_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimants', to='rewards.claimablebalance')),
            ],
        ),
    ]
